### ISSUE TITLE
关于FWFramework

### ISSUE THREAD

**Issue by james8023** [lszzy/FWFramework#1]
无法用pod集成到项目中，提示：找不到要克隆的远程分支0.6.1

**Comment by lszzy** [comment]
> 无法用pod集成到项目中，提示：找不到要克隆的远程分支0.6.1

解决方法：
1. 不指定pod版本号0.6.1，然后执行pod update，更新到最新版本。如果引入了subspecs报错的话，可参考如下配置：
pod 'FWFramework', :subspecs => ['FWFramework', 'Component/SDWebImage']

由于本库目前还在beta开发阶段，仅内部在使用，Api会经常变动，可能需要迁移报错方法到新的Api。后续稳定之后才会发布1.0正式版，给您造成的不便还请谅解。

**Comment by james8023** [comment]
好的，明白，谢谢 在2020年12月16日 20:28，wuyong 写道： 

无法用pod集成到项目中，提示：找不到要克隆的远程分支0.6.1

解决方法：

不指定pod版本号0.6.1，然后执行pod update，更新到最新版本。如果引入了subspecs报错的话，可参考如下配置：
pod 'FWFramework', :subspecs => ['FWFramework', 'Component/SDWebImage']

由于本库目前还在beta开发阶段，仅内部在使用，Api会经常变动，可能需要迁移报错方法到新的Api。后续稳定之后才会发布1.0正式版，给您造成的不便还请谅解。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/lszzy/FWFramework/issues/1#issuecomment-746215168",
"url": "https://github.com/lszzy/FWFramework/issues/1#issuecomment-746215168",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
