### ISSUE TITLE
有点小建议

### ISSUE THREAD

**Issue by vanehu** [lszzy/FWFramework#3]
框架是比较好
但是我认为能把繁重的UI解放出来就更简单一些
例如类似flexlib， 界面都配置化会节约很多时间来处理UI方面的事情
如果能把qmui类似的库结合flexlib再结合你的框架就简单很多了

**Comment by lszzy** [comment]
> 框架是比较好
> 但是我认为能把繁重的UI解放出来就更简单一些
> 例如类似flexlib， 界面都配置化会节约很多时间来处理UI方面的事情
> 如果能把qmui类似的库结合flexlib再结合你的框架就简单很多了

感谢您的建议，提的很好。

首先，本框架和qmui、flexlib可以同时使用，不冲突。[调皮]

再说一下本库的现状嘛，目前个人对于Framework和Application层的实现相对满意些，主要解决iOS开发中的一些常规和痛点问题，搭建项目架构，方便开发维护。对于每个组件，目标都是使用简单，不依赖太多，可以随意拿出来放到别的项目使用，不和现有项目产生冲突。

对于Component层，目前是一些常用组件，大部分是引入的第三方实用组件，目前感觉是有点臃肿的。这一层是可选的，可以根据个人喜好自己搭配UI组件，比如flexlib、qmui这种。后续等SwiftUI更成熟一些，会考虑重构整个框架实现。
